[toolchain]
# channel = "nightly"
channel = "stable"
# components = [ "rust-src", "rust-analyzer", "rustc-codegen-cranelift", "miri", "llvm-tools", "rust-docs-json" ]
components = [ "rust-src", "rust-analyzer" ]
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasip1",
    "wasm32-wasip2",
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl"
  ]
profile = "default"
